config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  root 'home#index'
  get 'home/about'

  post "/" => 'home#index'

  post 'thinkific/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password)}
         end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @client = IEX::Api::Client.new(
      publishable_token: 'Tpk_ccf8b92f0f0b405bbb17b313af8da443',
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    if params[:ticker] == ""
      @nothing = "Enter a stock, please!"
    elsif params[:ticker]
      @stock = @client.key_stats(params[:ticker])
      if !@stock
        @error = "Hey this doesn't exist, tyr again, make my day"
      end
    end

  end
  def about
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
    @client = IEX::Api::Client.new(
      publishable_token: 'Tpk_ccf8b92f0f0b405bbb17b313af8da443',
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
  end
  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
    @stock = Stock.find(id)
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "End of the line bub" if @ticker.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/controllers/thinkific_controller.rb
require 'securerandom' unless defined?(SecureRandom)

class ThinkificController < ApplicationController
  # Configuration
  THINKIFIC_API_KEY = "Replace with THINKIFIC_API_KEY"
  THINKIFIC_SUBDOMAIN = "Replace with THINKIFIC_SUBDOMAIN"

  def create
    if user_signed_in?
      user = current_user
    # if user = User.authenticate(params[:login], params[:password])
      # If the submitted credentials pass, then log user into Thinkific
      sign_into_thinkific(user)
    else
      render :new, :notice => "Invalid credentials"
    end
  end

  private

  def sign_into_thinkific(user)
    # This is the meat of the business, set up the parameters you wish
    # to forward to Thinkific. All parameters are documented in this page.


    iat = Time.now.to_i
    jti = "#{iat}/#{SecureRandom.hex(18)}"
    payload = JWT.encode({
      :iat   => iat - 500,
      :jti   => jti,
      :first_name  => user.first_name,
      :last_name => user.last_name,
      :email => user.email,
      :external_id => user.id
     }, THINKIFIC_API_KEY)
    redirect_to thinkific_sso_url(payload)
  end


  def thinkific_sso_url(payload)
    url = "http://#{THINKIFIC_SUBDOMAIN}.thinkific.com/api/sso/v2/sso/jwt?jwt=#{payload}"
    url += "&return_to=https://academy.manarugbycoach.com/courses/january-2021"
    url += "&error_url=#{URI.escape(params["error_url"])}" if params["error_url"].present?
    url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<br>
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissable" role="alert">
    <button class="close" data-dismiss="alert">
      <small><sup>x</sup></small>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/home/_footer.html.erb
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<center>Rory Manathunga Copyright 2019 - Present</center>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Stock This", root_path, class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "About", home_about_path, class:'nav-link' %>
      </li>
      <li class="nav-item active">
      <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Add Stock", new_stock_path, class:'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to "My Stocks", stocks_path, class:'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to "My Courses", thinkific_create_path, class:'nav-link', :method => :post %>
          </li>
          <li class="nav-item active">
            <%= link_to "My Account", edit_user_registration_path, class:'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to "Log Out", destroy_user_session_path, class:'nav-link', :method => :delete %>
          </li>
        <% else %>
        <li class="nav-item active">
          <%= link_to "Sign Up", new_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to "Login", new_user_session_path, class:'nav-link' %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About this dang ol pagee</h1>
<p>Testington</p>

app/views/home/index.html.erb
<h1>Stock This</h1>

<%= form_tag root_path, :method => 'POST' do %>
  <%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50 %>
  <%= submit_tag 'Lookup' %>
<% end %>
<br>
<% if @stock %>
  <% if @stock == "" %>
    That doesn't exist?!?!
  <% end %>
  <%= @stock.company_name %>
  <br>
  <%= @stock.employees %>
  <br>
  <%= @stock.week_52_high_dollar %>
  <br>
  <%= @stock.week_52_low_dollar %>
<% elsif @nothing %>
    <%= @nothing %>
<% end %>

<% if @error %>
  <%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock This!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <%= render "home/flash" %>
      <br>
      <%= yield %>
    </div>
    <%= render 'home/footer' %>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any?%>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker %>
  </div>

  <div class="field">
    <%= form.number_field :user_id,
      value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Current Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <% if stock.user_id == current_user.id %>

          <%  if stock.ticker == "" %>
            <%=  @nothing = "No Stock" %>
          <% elsif stock.ticker %>
              <% @company = @client.company(stock.ticker) %>
            <%  if !stock.ticker%>
              <%=  @error = "Incorrect" %>
            <%   end %>
          <%   end %>

        <tr>
          <td><%= @company.company_name %></td>
          <td>$<%= @client.price(stock.ticker) %></td>
          <td><%= link_to 'Show', stock %></td>
          <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
          <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker %>
</p>

<p>
  <strong>User:</strong>
  <%= @stock.user_id %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>